all_etfs = ["VOO", "SPY", "QQQ", "SCHD", "SQQQ", "JEPI", "VTI", "TMF", "TQQQ", "UVXY", "IVV", "TSLY", "VGT", "JEPQ",
            "LABU", "SPYI", "DIA", "VYM", "SPXU", "QYLD"]

short_list_for_testing = [
    'AAPL', 'TSLA', 'NIO', 'AMZN', 'GOOG', 'NVDA'
]

short_list_for_minimum_viability = [
    'TSLA', 'PLTR', 'AMD', 'AMZN', 'F', 'AAPL', 'NIO', 'SOFI', 'NKLA', 'BAC', 'NVDA', 'INTC', 'CCL', 'MARA', 'T',
    'LCID', 'RIVN', 'GOOGL', 'AI', 'NU', 'MSFT', 'PFE', 'PACW', 'SNAP', 'AAL', 'GOOG', 'OPEN', 'CVNA', 'PLUG', 'BBD',
    'UBER', 'RIOT', 'META', 'LUMN', 'VALE', 'KEY', 'WBD', 'PBR', 'DNA', 'WFC', 'ITUB', 'SWN', 'SPCE', 'BABA', 'VZ',
    'CSCO', 'AMC', 'CMCSA', 'MU', 'LYFT', 'PYPL', 'PCG', 'USB', 'GRAB', 'SIRI', 'NOK', 'SCHW', 'AFRM', 'SHOP', 'COIN',
    'HBAN', 'RIG', 'PARA', 'XOM', 'C', 'MRVL', 'SOUN', 'TLRY', 'NCLH', 'GOLD', 'XPEV', 'ABEV', 'GM', 'FCEL', 'TEVA',
    'KO', 'FUBO', 'TFC', 'DISH', 'KMI', 'NYCB', 'FHN', 'HPE', 'DIS', 'MPW', 'FCX', 'FTCH', 'U', 'M', 'CSX', 'TSM',
    'PINS', 'DKNG', 'KGC', 'DAL', 'INFY', 'MRO', 'JD', 'IQ', 'JPM'
]

medium_list_for_inital_processing = [
    'TSLA', 'PLTR', 'AMD', 'AMZN', 'F', 'AAPL', 'NIO', 'SOFI', 'NKLA', 'BAC', 'NVDA', 'INTC', 'CCL', 'MARA', 'T',
    'LCID', 'RIVN', 'GOOGL', 'AI', 'NU', 'MSFT', 'PFE', 'PACW', 'SNAP', 'AAL', 'GOOG', 'OPEN', 'CVNA', 'PLUG', 'BBD',
    'UBER', 'RIOT', 'META', 'LUMN', 'VALE', 'KEY', 'WBD', 'PBR', 'DNA', 'WFC', 'ITUB', 'SWN', 'SPCE', 'BABA', 'VZ',
    'CSCO', 'AMC', 'CMCSA', 'MU', 'LYFT', 'PYPL', 'PCG', 'USB', 'GRAB', 'SIRI', 'NOK', 'SCHW', 'AFRM', 'SHOP', 'COIN',
    'HBAN', 'RIG', 'PARA', 'XOM', 'C', 'MRVL', 'SOUN', 'TLRY', 'NCLH', 'GOLD', 'XPEV', 'ABEV', 'GM', 'FCEL', 'TEVA',
    'KO', 'FUBO', 'TFC', 'DISH', 'KMI', 'NYCB', 'FHN', 'HPE', 'DIS', 'MPW', 'FCX', 'FTCH', 'U', 'M', 'CSX', 'TSM',
    'PINS', 'DKNG', 'KGC', 'DAL', 'INFY', 'MRO', 'JD', 'IQ', 'JPM', 'CHPT', 'APE', 'JBLU', 'PTON', 'OXY', 'SQ', 'HUT',
    'ORCL', 'AGNC', 'LYG', 'PATH', 'TELL', 'LU', 'SLB', 'RF', 'RBLX', 'CLSK', 'GPS', 'IONQ', 'HAL', 'VTRS', 'KDP',
    'TIO', 'CLF', 'ET', 'UPST', 'ERIC', 'RUN', 'PDD', 'BSX', 'HBI', 'CVS', 'S', 'CFG', 'WBA', 'CPNG', 'BCS', 'FSR',
    'JOBY', 'QCOM', 'IMGN', 'NEM', 'BMY', 'DVN', 'HOOD', 'RLX', 'AMCR', 'BP', 'NKE', 'BTG', 'BBAI', 'NVTA', 'CVX',
    'HPQ', 'BEKE', 'LAZR', 'ATVI', 'MO', 'TAL', 'SABR', 'ETRN', 'LUV', 'LI', 'CVE', 'NEE', 'KHC', 'CTRA', 'WMB', 'MS',
    'ELAN', 'MRK', 'EOSE', 'UAL', 'NWL', 'FITB', 'NFLX', 'UAA', 'BKR', 'X', 'WW', 'HL', 'ON', 'ENVX', 'ROKU', 'WAL',
    'SBUX', 'CNHI', 'VFC', 'XP', 'JNJ', 'V', 'GERN', 'HST', 'TOST', 'CRM', 'GGB', 'CXAI', 'UMC', 'PR', 'EQT', 'TMUS',
    'SNOW', 'VLY', 'ABNB', 'BITF', 'EXC', 'PG', 'AVTR', 'AES', 'TME', 'APLD', 'GEVO', 'CX', 'MDLZ', 'MVIS', 'ZI', 'SYF',
    'ZION', 'COP', 'MDT', 'CARR', 'STEM', 'VOD', 'WMT', 'NVAX', 'ABBV', 'AMAT', 'AGEN', 'MET', 'UCAR', 'NET', 'WU',
    'FTI', 'ARDX', 'W', 'AR', 'GILD', 'GE', 'GFI', 'PANW', 'STNE', 'FIS', 'CTLT', 'APA', 'YMM', 'BA', 'TGT', 'AQN',
    'CL', 'KR', 'QBTS', 'PAGS', 'IOVA', 'ARR', 'BAX', 'GMDA', 'CDE', 'GSIT', 'MTCH', 'QS', 'CLVT', 'KOS', 'ASX', 'NRG',
    'VIPS', 'GT', 'KVUE', 'KSS', 'VRT', 'UEC', 'FTNT', 'BE', 'COTY', 'BK', 'JWN', 'SPWR', 'ABR', 'IBRX', 'BB', 'MCHP',
    'ABT', 'BILI', 'TXN', 'NOV', 'GLW', 'LILM', 'DDOG', 'AMRS', 'ATUS', 'HPP', 'TCOM', 'IPG', 'TJX', 'BRFS', 'MQ',
    'CHGG', 'DELL', 'PPL', 'ISEE', 'PSTG', 'VICI', 'TECK', 'EBAY', 'BTBT', 'AG', 'SE', 'TWLO', 'DBX', 'PEAK', 'PEP',
    'AEO', 'AA', 'DOW', 'STLA', 'AZN', 'IBM', 'IVZ', 'SU', 'LVS', 'ROIV', 'DHC', 'SHEL', 'BTI', 'CFLT', 'ALLY', 'ONON',
    'NLY', 'HD', 'MVST', 'MOS', 'MGM', 'FLEX', 'CCJ', 'ACI', 'VLO', 'ZM', 'RTX', 'WY', 'PM', 'TGTX', 'GPK', 'MNST',
    'EPD', 'AUR', 'KIM', 'BTE', 'ARRY', 'RRC', 'CAG', 'CMA', 'SO', 'HMY', 'BLUE', 'XFOR', 'FOXA', 'AIG', 'VNO', 'O',
    'CANO', 'DM', 'IBN', 'DOCU', 'D', 'CIG', 'PAAS', 'BDTX', 'ENPH', 'TDOC', 'CRWD', 'OVV', 'INAB', 'CHWY', 'NI',
    'NOVA', 'FE', 'JNPR', 'REAL', 'GME', 'MPC', 'PTEN', 'WDC', 'DEI', 'GNW', 'EVGO', 'BX', 'RITM', 'IAG', 'RKLB',
    'ADBE', 'ZIM', 'RCL', 'TSN', 'CRK', 'MCRB', 'BBWI', 'JCI', 'FI', 'FL', 'MMM', 'IOT', 'PAYO', 'SBSW', 'SID', 'CNP',
    'BHC', 'OPK', 'PACB', 'TTD', 'UPS', 'WULF', 'CTSH', 'CPG', 'ACHR', 'LESL', 'PK', 'MUFG', 'PAA', 'AGL', 'NEX',
    'VKTX', 'COMP', 'STM', 'TOP', 'PNC', 'COMM', 'DD', 'HIMS', 'DASH', 'MBLY', 'ADI', 'UNH', 'OWL', 'NGD', 'EOG', 'BTU',
    'STWD', 'WOLF', 'ADT', 'MRNA', 'EQH', 'DNN', 'ETSY', 'GIS', 'ANET', 'SFIX', 'FRO', 'PSX', 'DHR', 'VST', 'UNIT',
    'NDAQ', 'LTHM', 'MTTR', 'BRK.B', 'OPCH', 'EMR', 'IP', 'UBS', 'RIO', 'ENB', 'LNC', 'MRSN', 'CNC', 'BLDP', 'VCIG',
    'HLN', 'FAST', 'XEL', 'PLD', 'SPR', 'CHRS', 'CAT', 'OKE', 'TPR', 'PRST', 'COF', 'GSK', 'UA', 'ING', 'MFC', 'GEHC',
    'MNKD', 'AXP', 'SAN', 'BZ', 'BDN', 'DLR', 'COHR', 'DHI', 'MLCO', 'EQNR', 'LLY', 'ABCL', 'KKR', 'CTVA', 'PHM',
    'FSLY', 'IEP', 'DG', 'KPTI'
]

all_by_three_month_average_trading_volume = \
    ['TSLA', 'PLTR', 'AMD', 'AMZN', 'F', 'AAPL', 'NIO', 'SOFI', 'NKLA', 'BAC', 'NVDA', 'INTC', 'CCL',
     'MARA', 'T', 'LCID', 'RIVN', 'GOOGL', 'AI', 'NU', 'MSFT', 'PFE', 'PACW', 'SNAP', 'AAL', 'GOOG',
     'OPEN', 'CVNA', 'PLUG', 'BBD', 'UBER', 'RIOT', 'META', 'LUMN', 'VALE', 'KEY', 'WBD', 'PBR', 'DNA',
     'WFC', 'ITUB', 'SWN', 'SPCE', 'BABA', 'VZ', 'CSCO', 'AMC', 'CMCSA', 'MU', 'LYFT', 'PYPL', 'PCG',
     'USB', 'GRAB', 'SIRI', 'NOK', 'SCHW', 'AFRM', 'SHOP', 'COIN', 'HBAN', 'RIG', 'PARA', 'XOM', 'C',
     'MRVL', 'SOUN', 'TLRY', 'NCLH', 'GOLD', 'XPEV', 'ABEV', 'GM', 'FCEL', 'TEVA', 'KO', 'FUBO', 'TFC',
     'DISH', 'KMI', 'NYCB', 'FHN', 'HPE', 'DIS', 'MPW', 'FCX', 'FTCH', 'U', 'M', 'CSX', 'TSM', 'PINS',
     'DKNG', 'KGC', 'DAL', 'INFY', 'MRO', 'JD', 'IQ', 'JPM', 'CHPT', 'APE', 'JBLU', 'PTON', 'OXY', 'SQ',
     'HUT', 'ORCL', 'AGNC', 'LYG', 'PATH', 'TELL', 'LU', 'SLB', 'RF', 'RBLX', 'CLSK', 'GPS', 'IONQ', 'HAL',
     'VTRS', 'KDP', 'TIO', 'CLF', 'ET', 'UPST', 'ERIC', 'RUN', 'PDD', 'BSX', 'HBI', 'CVS', 'S', 'CFG',
     'WBA', 'CPNG', 'BCS', 'FSR', 'JOBY', 'QCOM', 'IMGN', 'NEM', 'BMY', 'DVN', 'HOOD', 'RLX', 'AMCR', 'BP',
     'NKE', 'BTG', 'BBAI', 'NVTA', 'CVX', 'HPQ', 'BEKE', 'LAZR', 'ATVI', 'MO', 'TAL', 'SABR', 'ETRN',
     'LUV', 'LI', 'CVE', 'NEE', 'KHC', 'CTRA', 'WMB', 'MS', 'ELAN', 'MRK', 'EOSE', 'UAL', 'NWL', 'FITB',
     'NFLX', 'UAA', 'BKR', 'X', 'WW', 'HL', 'ON', 'ENVX', 'ROKU', 'WAL', 'SBUX', 'CNHI', 'VFC', 'XP',
     'JNJ', 'V', 'GERN', 'HST', 'TOST', 'CRM', 'GGB', 'CXAI', 'UMC', 'PR', 'EQT', 'TMUS', 'SNOW', 'VLY',
     'ABNB', 'BITF', 'EXC', 'PG', 'AVTR', 'AES', 'TME', 'APLD', 'GEVO', 'CX', 'MDLZ', 'MVIS', 'ZI', 'SYF',
     'ZION', 'COP', 'MDT', 'CARR', 'STEM', 'VOD', 'WMT', 'NVAX', 'ABBV', 'AMAT', 'AGEN', 'MET', 'UCAR',
     'NET', 'WU', 'FTI', 'ARDX', 'W', 'AR', 'GILD', 'GE', 'GFI', 'PANW', 'STNE', 'FIS', 'CTLT', 'APA',
     'YMM', 'BA', 'TGT', 'AQN', 'CL', 'KR', 'QBTS', 'PAGS', 'IOVA', 'ARR', 'BAX', 'GMDA', 'CDE', 'GSIT',
     'MTCH', 'QS', 'CLVT', 'KOS', 'ASX', 'NRG', 'VIPS', 'GT', 'KVUE', 'KSS', 'VRT', 'UEC', 'FTNT', 'BE',
     'COTY', 'BK', 'JWN', 'SPWR', 'ABR', 'IBRX', 'BB', 'MCHP', 'ABT', 'BILI', 'TXN', 'NOV', 'GLW', 'LILM',
     'DDOG', 'AMRS', 'ATUS', 'HPP', 'TCOM', 'IPG', 'TJX', 'BRFS', 'MQ', 'CHGG', 'DELL', 'PPL', 'ISEE',
     'PSTG', 'VICI', 'TECK', 'EBAY', 'BTBT', 'AG', 'SE', 'TWLO', 'DBX', 'PEAK', 'PEP', 'AEO', 'AA', 'DOW',
     'STLA', 'AZN', 'IBM', 'IVZ', 'SU', 'LVS', 'ROIV', 'DHC', 'SHEL', 'BTI', 'CFLT', 'ALLY', 'ONON', 'NLY',
     'HD', 'MVST', 'MOS', 'MGM', 'FLEX', 'CCJ', 'ACI', 'VLO', 'ZM', 'RTX', 'WY', 'PM', 'TGTX', 'GPK',
     'MNST', 'EPD', 'AUR', 'KIM', 'BTE', 'ARRY', 'RRC', 'CAG', 'CMA', 'SO', 'HMY', 'BLUE', 'XFOR', 'FOXA',
     'AIG', 'VNO', 'O', 'CANO', 'DM', 'IBN', 'DOCU', 'D', 'CIG', 'PAAS', 'BDTX', 'ENPH', 'TDOC', 'CRWD',
     'OVV', 'INAB', 'CHWY', 'NI', 'NOVA', 'FE', 'JNPR', 'REAL', 'GME', 'MPC', 'PTEN', 'WDC', 'DEI', 'GNW',
     'EVGO', 'BX', 'RITM', 'IAG', 'RKLB', 'ADBE', 'ZIM', 'RCL', 'TSN', 'CRK', 'MCRB', 'BBWI', 'JCI', 'FI',
     'FL', 'MMM', 'IOT', 'PAYO', 'SBSW', 'SID', 'CNP', 'BHC', 'OPK', 'PACB', 'TTD', 'UPS', 'WULF', 'CTSH',
     'CPG', 'ACHR', 'LESL', 'PK', 'MUFG', 'PAA', 'AGL', 'NEX', 'VKTX', 'COMP', 'STM', 'TOP', 'PNC', 'COMM',
     'DD', 'HIMS', 'DASH', 'MBLY', 'ADI', 'UNH', 'OWL', 'NGD', 'EOG', 'BTU', 'STWD', 'WOLF', 'ADT', 'MRNA',
     'EQH', 'DNN', 'ETSY', 'GIS', 'ANET', 'SFIX', 'FRO', 'PSX', 'DHR', 'VST', 'UNIT', 'NDAQ', 'LTHM',
     'MTTR', 'BRK.B', 'OPCH', 'EMR', 'IP', 'UBS', 'RIO', 'ENB', 'LNC', 'MRSN', 'CNC', 'BLDP', 'VCIG',
     'HLN', 'FAST', 'XEL', 'PLD', 'SPR', 'CHRS', 'CAT', 'OKE', 'TPR', 'PRST', 'COF', 'GSK', 'UA', 'ING',
     'MFC', 'GEHC', 'MNKD', 'AXP', 'SAN', 'BZ', 'BDN', 'DLR', 'COHR', 'DHI', 'MLCO', 'EQNR', 'LLY', 'ABCL',
     'KKR', 'CTVA', 'PHM', 'FSLY', 'IEP', 'DG', 'KPTI', 'LOW', 'ZS', 'ZH', 'MP', 'BEN', 'DT', 'RDFN',
     'GTLB', 'APP', 'INVH', 'APH', 'CG', 'VRM', 'GRRR', 'FSM', 'AVGO', 'TRIP', 'WOOF', 'SNDL', 'HTZ',
     'DUK', 'PBF', 'PGR', 'NTR', 'CZR', 'ADM', 'MA', 'NNOX', 'ZTO', 'AU', 'TSP', 'CNX', 'KC', 'DNB',
     'CSGP', 'INFN', 'BXMT', 'PENN', 'FIGS', 'MRVI', 'BYND', 'SYNH', 'DB', 'BHP', 'BCRX', 'AGI', 'PSNY',
     'SLG', 'AEP', 'ALLO', 'RCM', 'EW', 'LLAP', 'CWK', 'BUD', 'STT', 'HWM', 'ARMK', 'Z', 'LBRT', 'PGY',
     'MAC', 'ACN', 'CF', 'SHLS', 'BWA', 'PCAR', 'WEN', 'CCI', 'OKTA', 'EXPE', 'SGMO', 'OTLY', 'EXEL',
     'BIDU', 'PAGP', 'BIG', 'MAT', 'AEM', 'CRBG', 'WRK', 'MODG', 'CPB', 'MCD', 'FOLD', 'AUPH', 'ENLC',
     'BLDR', 'CPRI', 'SYY', 'DXCM', 'SAND', 'CAVA', 'AM', 'FATE', 'SMCI', 'CAN', 'BMBL', 'NAT', 'VVV',
     'SLDP', 'GOTU', 'DHT', 'STAG', 'ESPR', 'APO', 'FSLR', 'WELL', 'UNP', 'TALO', 'LXRX', 'NVTS', 'LEVI',
     'PEG', 'TDS', 'AAP', 'SLM', 'FNB', 'APPS', 'AZUL', 'FRSH', 'DINO', 'K', 'RAD', 'LXP', 'VSCO', 'ASTS',
     'TD', 'BBY', 'DRH', 'VTR', 'TAP', 'ALIT', 'WYNN', 'GPN', 'HON', 'AMGN', 'TS', 'CNK', 'HR', 'ME',
     'FYBR', 'ASAN', 'BFLY', 'LBTYK', 'CRBU', 'CCO', 'AFL', 'RXT', 'VTNR', 'EL', 'EXK', 'STX', 'BTAI',
     'NWSA', 'EDIT', 'HRTX', 'ALB', 'CAH', 'LSCC', 'RPRX', 'PEB', 'EDR', 'ROST', 'UNVR', 'SMFG', 'GS',
     'CEG', 'LEN', 'IRWD', 'HZNP', 'MT', 'SPPI', 'CIM', 'NXPI', 'DLTR', 'WTI', 'UDR', 'UPWK', 'NTAP',
     'CMS', 'ICE', 'CPRT', 'ONB', 'AMH', 'RIGL', 'XYL', 'SONO', 'VERU', 'PLX', 'PGRE', 'LPSN', 'AXTA',
     'HBM', 'IR', 'TMC', 'MTG', 'PRU', 'GH', 'FGEN', 'REI', 'PAYX', 'FTV', 'KMX', 'HRL', 'CRDO', 'ARNC',
     'ADMA', 'XPO', 'RLJ', 'GOSS', 'OCEA', 'JBGS', 'SBRA', 'BN', 'SIX', 'RXRX', 'FREY', 'BJ', 'PL', 'HCP',
     'INDI', 'FARM', 'NVST', 'PTRA', 'APTV', 'NNDM', 'GCI', 'AMRN', 'BRX', 'BLNK', 'MREO', 'NATI', 'ETN',
     'SMMT', 'NOTE', 'COLB', 'PXD', 'AMT', 'DFS', 'ASRT', 'AVDX', 'WDAY', 'SHO', 'TEAM', 'INCY', 'UL',
     'OSCR', 'OGN', 'EA', 'OHI', 'A', 'CPRX', 'EQRX', 'NVS', 'KNX', 'CNQ', 'PRVA', 'OSTK', 'WSC', 'UGI',
     'MANU', 'GEO', 'FDX', 'EXTR', 'ES', 'ALT', 'CP', 'DBI', 'TPX', 'EQX', 'WIT', 'CTXR', 'MDB', 'EC',
     'IFF', 'ATRA', 'OLPX', 'CDNS', 'CUK', 'ALL', 'BALL', 'HUN', 'ZTS', 'YPF', 'FULT', 'SKX', 'HRB',
     'YEXT', 'CBAY', 'CIEN', 'SWKS', 'SQM', 'VIAV', 'OUT', 'TRP', 'DOCS', 'AYX', 'CHS', 'PCT', 'URG',
     'DXC', 'MAS', 'SITC', 'REXR', 'USFD', 'MGY', 'LYB', 'SM', 'OTIS', 'TAK', 'CBRE', 'ACGL', 'TGNA',
     'OZK', 'ED', 'BOWL', 'CROX', 'FANG', 'RC', 'RKT', 'NXE', 'WMG', 'RNG', 'URBN', 'FUTU', 'INVZ', 'BBIO',
     'LBTYA', 'ASO', 'IRT', 'BILL', 'VMEO', 'EXAS', 'MPLN', 'AKBA', 'LYV', 'BKD', 'HOG', 'CLNE', 'YUM',
     'DE', 'DBRG', 'DLO', 'HDB', 'COST', 'EQR', 'HAYW', 'CYH', 'INTU', 'WPM', 'VIV', 'CB', 'DOC', 'SG',
     'MUR', 'ILPT', 'ANF', 'NEXT', 'XRAY', 'JMIA', 'LC', 'AHI', 'ETWO', 'SFM', 'FLO', 'SKIN', 'RLAY',
     'EVA', 'KBH', 'XRX', 'TTWO', 'BXP', 'SMTC', 'HYLN', 'WRB', 'MAR', 'MMC', 'ASB', 'CI', 'TER', 'HLT',
     'KIND', 'BLMN', 'LITE', 'EDU', 'EGHT', 'KD', 'KMB', 'SPRY', 'NEOG', 'APLE', 'IMMP', 'HIG', 'ADP',
     'AZEK', 'EB', 'TRU', 'STLD', 'ENTG', 'DADA', 'MPLX', 'TV', 'HLX', 'CXM', 'MBC', 'FTCI', 'HSBC',
     'CVBF', 'YUMC', 'CARG', 'APLS', 'TOL', 'HAS', 'LMND', 'IAUX', 'GTES', 'CD', 'HES', 'TMO', 'LULU',
     'DAN', 'MMP', 'EGO', 'PDCE', 'SWK', 'SMAR', 'DOCN', 'NUE', 'PD', 'FSP', 'TRGP', 'AEG', 'PRCH', 'ALTO',
     'ERJ', 'OMC', 'IGT', 'CHD', 'ISRG', 'CUZ', 'ABCM', 'SLQT', 'SNV', 'NOW', 'GENI', 'NWG', 'LAC', 'BVN',
     'LNG', 'CC', 'BBVA', 'SBS', 'ORI', 'SRPT', 'UUUU', 'TCRX', 'ALGM', 'EVLV', 'PDM', 'ALK', 'SPOT',
     'HOUS', 'LIN', 'CUBE', 'FERG', 'TRUP', 'NOG', 'RES', 'SBH', 'ETR', 'SDA', 'RDN', 'DICE', 'SHCR',
     'GWH', 'EIX', 'FLR', 'SUZ', 'MKC', 'HLMN', 'ZWS', 'ARQQ', 'ROL', 'HTHT', 'HKD', 'BKSY', 'HP', 'MTB',
     'SSRM', 'ACVA', 'RMBS', 'EBS', 'TT', 'VMW', 'HUDI', 'ETNB', 'AMBP', 'KRG', 'SMRT', 'SANA', 'NAVI',
     'PLNT', 'CPE', 'G', 'PLAY', 'ADSK', 'EURN', 'AMPS', 'PPG', 'KDNY', 'SPG', 'ZBH', 'DK', 'SAVE', 'CCK',
     'GOGL', 'AKAM', 'CME', 'HOLX', 'DVAX', 'RUM', 'EAF', 'MDU', 'ESRT', 'PBI', 'MGNI', 'DKS', 'ABST',
     'TTE', 'SNY', 'CADE', 'HLIT', 'BF.B', 'CTKB', 'WM', 'SPLK', 'VLD', 'ULCC', 'FIVN', 'CRON', 'HUYA',
     'CDAY', 'SGEN', 'GFS', 'ICPT', 'FTAI', 'INMD', 'TEL', 'ALKS', 'CRSP', 'RVLV', 'COLD', 'HLF', 'EWBC',
     'NTNX', 'ILMN', 'LICY', 'PFG', 'CE', 'TVTX', 'THC', 'ALDX', 'SHW', 'MTDR', 'PUMP', 'FOUR', 'LNT',
     'KBR', 'NFE', 'QUBT', 'NCR', 'DAR', 'CIFR', 'NXT', 'RVNC', 'IRM', 'NVO', 'TU', 'GOL', 'CHX', 'WEC',
     'BORR', 'AIV', 'EBR', 'CARA', 'NSC', 'GDDY', 'NE', 'HIVE', 'OLN', 'ENIC', 'GLBE', 'FBP', 'ACAD',
     'DFLI', 'HTGC', 'MCW', 'GPRO', 'RNA', 'LRCX', 'ARQT', 'TWST', 'WBS', 'XERS', 'BRO', 'CNM', 'WISH',
     'AHCO', 'MAXN', 'BKKT', 'WT', 'NTRS', 'DV', 'MIR', 'BOX', 'HCA', 'SDGR', 'SEE', 'IHRT', 'CHK', 'ABC',
     'DRI', 'FLNC', 'MOMO', 'AMWL', 'FNF', 'AMTX', 'GRPN', 'UGP', 'TROX', 'DAWN', 'GOOS', 'CCCS', 'DTE',
     'OCUL', 'TROW', 'ICL', 'LZ', 'RJF', 'EGY', 'EYE', 'CERS', 'PLTK', 'SELB', 'BAK', 'SES', 'AEE', 'BG',
     'SYK', 'TXT', 'YOU', 'CELH', 'FOX', 'EXPI', 'NG', 'NVCR', 'ELV', 'OPI', 'BOH', 'GDS', 'ESI', 'KT',
     'EVH', 'DDD', 'FND', 'BNS', 'QUOT', 'KRC', 'TSCO', 'CCCC', 'ORGN', 'QRVO', 'VRTX', 'CENX', 'UNM',
     'PECO', 'BCE', 'VRRM', 'ZFOX', 'CERT', 'EXPD', 'GTN', 'BERY', 'AAOI', 'TRV', 'BIRD', 'ARCO', 'UWMC',
     'IONS', 'BMRN', 'RXO', 'ATEC', 'PGEN', 'CMRX', 'HA', 'TNDM', 'SRE', 'TMHC', 'TWOU', 'ESTE', 'ESTC',
     'FHI', 'PNR', 'RPD', 'SVM', 'IREN', 'GNRC', 'PTGX', 'NTES', 'HALO', 'NRGV', 'FLYW', 'AGBA', 'BURL',
     'CLX', 'TPH', 'ARI', 'BKU', 'ARLO', 'SCCO', 'HIW', 'CM', 'LW', 'HOMB', 'NSTG', 'CHRW', 'AUGX', 'RTL',
     'KEYS', 'AXON', 'ERF', 'RWT', 'SCS', 'CNI', 'SSNC', 'LYEL', 'CSIQ', 'PRM', 'COUR', 'CVI', 'EVRG',
     'IQV', 'GD', 'STNG', 'GMED', 'HMC', 'ATI', 'AZTA', 'STZ', 'HUM', 'LKQ', 'RYAM', 'EXR', 'FFWM', 'TTI',
     'TBLA', 'AXL', 'VET', 'GLPI', 'ADTN', 'ALHC', 'BDX', 'OTLK', 'TXRH', 'VOYA', 'ZETA', 'CRVS', 'TRMB',
     'TWO', 'YETI', 'ALLK', 'AMX', 'LSXMK', 'EMAN', 'SPGI', 'VRSK', 'DO', 'GNTX', 'WH', 'RSG', 'TECH',
     'NERV', 'PHG', 'GDRX', 'LILAK', 'LSPD', 'PLYA', 'SEDG', 'HOPE', 'GNL', 'VECT', 'CCEP', 'AEVA', 'ROIC',
     'HNST', 'RCUS', 'OLLI', 'VNET', 'SMR', 'PRPL', 'VEEV', 'JEF', 'CBD', 'CDTX', 'CHTR', 'SHC', 'TGI',
     'ITW', 'GETY', 'QSR', 'AMRX', 'CRC', 'MFA', 'TWKS', 'HSY', 'OGE', 'VSH', 'PLBY', 'MGA', 'ARES',
     'NTRA', 'IMVT', 'VIRT', 'DNMR', 'ELF', 'OLO', 'BNL', 'MNSO', 'TENB', 'CNDT', 'TEF', 'OR', 'NTCO',
     'WPC', 'WIX', 'LNTH', 'OUST', 'SLGC', 'RADI', 'NNN', 'MDRX', 'MRTX', 'TIGR', 'FBIN', 'CRH', 'BIIB',
     'ECVT', 'PRAX', 'SBLK', 'PCOR', 'WSM', 'NMR', 'PRGO', 'CWH', 'WTRG', 'ARWR', 'KLAC', 'STKL', 'AOS',
     'ECL', 'RHI', 'ST', 'NTLA', 'ORGO', 'DCFC', 'JBL', 'NEP', 'NVT', 'BHVN', 'LDOS', 'AEHR', 'ACIU',
     'TLS', 'DOUG', 'WAB', 'HAIN', 'HASI', 'BRSP', 'TREX', 'ADPT', 'GES', 'XPOF', 'SKT', 'EAT', 'INSM',
     'ARE', 'BKI', 'WB', 'LSXMA', 'BARK', 'LHX', 'IMUX', 'BRBR', 'GLNG', 'CAKE', 'RL', 'GFL', 'LMT',
     'PRMW', 'PARR', 'UE', 'ZUO', 'QGEN', 'ZNTL', 'AMLX', 'AVDL', 'ANNX', 'ATAI', 'ASML', 'CDW', 'FHB',
     'OI', 'SNPS', 'DNUT', 'NRDY', 'MC', 'VNT', 'DGX', 'FMC', 'BIGC', 'AME', 'PFGC', 'WTTR', 'CMI', 'CWEN',
     'KOPN', 'CDLX', 'BSY', 'AER', 'MKFG', 'SIG', 'PLRX', 'BRZE', 'IAS', 'TPIC', 'AMKR', 'ULTA', 'DX',
     'DQ', 'RVMD', 'SCI', 'GSM', 'INN', 'SVC', 'LTH', 'PVH', 'SAP', 'SHOO', 'AVXL', 'ALV', 'LAUR', 'PCVX',
     'LTCH', 'IVR', 'SFL', 'NEO', 'EYPT', 'PSTX', 'SLRN', 'SILV', 'PRTK', 'KZR', 'BFH', 'PSA', 'TGB',
     'JXN', 'GGG', 'NYT', 'ASPN', 'DEA', 'URI', 'EBC', 'CHKP', 'CUTR', 'MSTR', 'WWW', 'MRNS', 'EMN',
     'WRBY', 'SPT', 'QFIN', 'GRWG', 'ORMP', 'AXSM', 'LEGN', 'GRTS', 'MNDY', 'NCNO', 'ALC', 'CXW', 'ACM',
     'AJG', 'ATO', 'BAH', 'GCT', 'SNN', 'MCK', 'AWK', 'CALM', 'BMEA', 'ADC', 'ASAI', 'MWA', 'IRDM', 'GPC',
     'SBGI', 'SNDX', 'JHG', 'RELY', 'TXG', 'CDXS', 'VUZI', 'LEG', 'SJM', 'LPX', 'NMRK', 'GO', 'EVRI',
     'ORC', 'VRNS', 'FTDR', 'BYD', 'OC', 'EPRT', 'ROVR', 'KURA', 'BRKR', 'PINC', 'FROG', 'OPRA', 'CYTK',
     'CDNA', 'PLCE', 'AIRC', 'SGH', 'WCN', 'VAL', 'PTCT', 'PDSB', 'APAM', 'XHR', 'SHAK', 'KW', 'BROS',
     'LWLG', 'REG', 'SYM', 'LXU', 'AVPT', 'TDC', 'FLS', 'IBKR', 'CFFN', 'MAG', 'ELS', 'TW', 'ODFL', 'UBSI',
     'EQC', 'POR', 'SEAS', 'HSIC', 'PERI', 'BWXT', 'TEX', 'MFG', 'VIR', 'MSI', 'LBRDK', 'AON', 'GBCI',
     'GNK', 'EU', 'PDCO', 'RENT', 'ACET', 'CRI', 'TWNK', 'HIMX', 'VTYX', 'SPWH', 'GPRE', 'FWONK', 'CTV',
     'PH', 'GXO', 'PPC', 'LL', 'FVRR', 'SSYS', 'LPLA', 'TCN', 'BEAM', 'FIBK', 'NINE', 'SPB', 'AJRD',
     'CSTM', 'ADNT', 'PWR', 'RVTY', 'NUVA', 'BOOT', 'RY', 'AROC', 'DH', 'QURE', 'APD', 'WES', 'TSEM',
     'WCC', 'GTHX', 'ONCY', 'NEWR', 'FULC', 'TSVT', 'RH', 'ALSN', 'CNO', 'DOV', 'LUNR', 'SONY', 'FIVE',
     'TRTN', 'VMC', 'ACDC', 'LEV', 'RETA', 'EFC', 'FR', 'TAST', 'SBAC', 'IDYA', 'ALLE', 'PMT', 'PGNY',
     'MDXG', 'SAVA', 'STGW', 'MXL', 'PTC', 'RELX', 'DNLI', 'SLCA', 'NARI', 'UNFI', 'CGNX', 'KMT', 'LAZ',
     'TERN', 'OMF', 'H', 'ICLR', 'AEL', 'DOLE', 'NWBI', 'CMC', 'ACRE', 'HGV', 'GRMN', 'WWE', 'L', 'LFST',
     'BGS', 'SQSP', 'UIS', 'LPRO', 'OMI', 'DTC', 'CPT', 'MLKN', 'COGT', 'AHT', 'PWSC', 'FOCS', 'PB', 'SMG',
     'ROK', 'AVIR', 'SUM', 'JKS', 'NSA', 'MCO', 'NWS', 'EFX', 'GRFS', 'KTOS', 'SJT', 'AVB', 'NAPA', 'NBIX',
     'WHR', 'ZURA', 'LCTX', 'NETI', 'AMPL', 'WDH', 'ARAY', 'SSTK', 'IART', 'RPAY', 'ITCI', 'TK', 'EH',
     'AKR', 'DRS', 'GWRE', 'TNL', 'JKHY', 'ABUS', 'JBHT', 'BVS', 'ASC', 'GGAL', 'AKRO', 'PNT', 'OIS',
     'HCSG', 'LGF.B', 'PBA', 'BSBR', 'NBTX', 'ERAS', 'CLS', 'EZPW', 'JBI', 'TDUP', 'ATSG', 'SBCF', 'WBX',
     'OFC', 'ALGN', 'OMER', 'FINV', 'RYTM', 'ACCD', 'ARHS', 'UIHC', 'RNW', 'OII', 'TNYA', 'LSI', 'AMED',
     'LIFE', 'FOSL', 'WEAV', 'AUTL', 'RCKT', 'ATMU', 'ABSI', 'PNW', 'SB', 'DNOW', 'RYAN', 'AMN', 'ASTL',
     'QTWO', 'PI', 'VERA', 'HESM', 'CALX', 'HOUR', 'BHIL', 'CSTL', 'TDW', 'FRPT', 'BNTX', 'MDC', 'SIGA',
     'FIP', 'CVAC', 'BBAR', 'PNFP', 'SWTX', 'EPAM', 'SEAT', 'NOC', 'SGRY', 'ATEN', 'INVA', 'EHAB', 'TCS',
     'VGR', 'UHS', 'PRTS', 'DXLG', 'YELP', 'BL', 'XMTR', 'NIR', 'LVTX', 'DTM', 'SKYW', 'VRDN', 'VERI',
     'OSW', 'CMRE', 'WNC', 'RARE', 'WFRD', 'MERC', 'LADR', 'NTST', 'ELME', 'WAFD', 'AL', 'SFWL', 'SLI',
     'CRMD', 'SWAV', 'BRY', 'ACRS', 'J', 'VYGR', 'CIVI', 'KN', 'FDMT', 'RBBN', 'UCBI', 'PKG', 'PTLO',
     'VCYT', 'ZYME', 'STR', 'BENF', 'GPMT', 'VERV', 'QSI', 'GTX', 'FCF', 'DVA', 'TALS', 'VTLE', 'OABI',
     'QNST', 'LFCR', 'CORT', 'ACHC', 'GTLS', 'PPBI', 'ZGN', 'MORF', 'SGML', 'DOYU', 'ACIW', 'DPZ', 'STAA',
     'BRKL', 'ACLX', 'COCO', 'LEA', 'SAGE', 'RNLX', 'MTZ', 'CNSL', 'LH', 'FRGE', 'SRC', 'WMS', 'SOVO',
     'SYNA', 'ZIP', 'RMD', 'TMDX', 'MKSI', 'ALNY', 'TASK', 'NVRO', 'CBSH', 'CVII', 'SNBR', 'WKC', 'CEIX',
     'SUI', 'NRDS', 'IAC', 'FFIV', 'CBOE', 'KOD', 'MIRM', 'PIII', 'HEPS', 'DUOL', 'BLK', 'ACMR', 'PZZA',
     'SMPL', 'UDMY', 'SF', 'WHD', 'WING', 'MHK', 'BPMC', 'OSUR', 'KODK', 'HWC', 'AQST', 'EHC', 'FLWS',
     'SPNT', 'PACK', 'BC', 'FMS', 'KAR', 'RMTI', 'AGRO', 'POWW', 'SFNC', 'AY', 'NYMT', 'IMMR', 'AN', 'YY',
     'NR', 'ZLAB', 'ADEA', 'CTRE', 'MAA', 'LOCO', 'GRTX', 'VECO', 'PLAB', 'ASND', 'PYXS', 'IFRX', 'AGR',
     'AGCO', 'APGB', 'MPWR', 'CRUS', 'PNM', 'RGEN', 'VIST', 'SXC', 'HCC', 'MRC', 'DCGO', 'EXFY', 'OPTN',
     'CINF', 'DOX', 'SCLX', 'SEM', 'XPRO', 'RPM', 'CMPX', 'GSL', 'REGN', 'COOP', 'FFIN', 'LOGI', 'TKR',
     'BANC', 'CFR', 'TTMI', 'AVY', 'GDYN', 'NGL', 'TPG', 'EOLS', 'REZI', 'PODD', 'HMST', 'AMP', 'INSW',
     'SSB', 'EYEN', 'REPL', 'SDRL', 'BR', 'KNTE', 'WERN', 'VNDA', 'AXNX', 'TRNO', 'FTS', 'BUR', 'MRCY',
     'PCRX', 'CIO', 'THO', 'SGHC', 'WAT', 'INZY', 'MD', 'FREE', 'NJR', 'HQY', 'SILK', 'DRVN', 'LQDA',
     'CLB', 'TALK', 'VTEX', 'CAL', 'CLDX', 'SNDR', 'TBPH', 'CLBR', 'GIL', 'BMO', 'CUBI', 'ANGI', 'HUBS',
     'SIMO', 'MYGN', 'TH', 'FORG', 'SD', 'JAZZ', 'CBRL', 'ACCO', 'LPG', 'CDMO', 'AUB', 'AMBA', 'PAYC',
     'OSG', 'CXT', 'NAAS', 'AVT', 'CERE', 'AVID', 'DYN', 'HXL', 'ALVR', 'LNW', 'PII', 'MSCI', 'IMAX',
     'HRMY', 'EBIX', 'PKST', 'SNCY', 'HOLO', 'JAMF', 'GL', 'SEEL', 'KYMR', 'IRBT', 'RDNT', 'PETS', 'ZUMZ',
     'GFF', 'DCPH', 'IT', 'FAF', 'SEIC', 'VZIO', 'ADV', 'BPOP', 'UXIN', 'SLAB', 'SEMR', 'HROW', 'ACLS',
     'RCAT', 'ASH', 'WTFC', 'SOL', 'VBTX', 'STRO', 'NVRI', 'RPT', 'ALEC', 'QD', 'SWX', 'PFS', 'VATE',
     'HELE', 'EVER', 'OSK', 'BGRY', 'CRL', 'RHP', 'NOMD', 'WTW', 'GIII', 'TIMB', 'BCAB', 'SKM', 'DOMO',
     'HLI', 'CMAX', 'PRAA', 'AVA', 'BEPC', 'NFG', 'SPHR', 'REKR', 'BHF', 'AGS', 'MGNX', 'SWBI', 'FLT',
     'INTA', 'VRE', 'INOD', 'GOGO', 'NUS', 'TTC', 'EHTH', 'DDL', 'GLOB', 'SON', 'GROY', 'RAMP', 'JSPR',
     'BW', 'SLGN', 'IMTX', 'VSTO', 'SVRA', 'FRT', 'ATOM', 'ROP', 'PGTI', 'FCPT', 'ESMT', 'SCPL', 'JELD',
     'RNR', 'RRR', 'TGLS', 'RYN', 'AKTS', 'EPR', 'DCI', 'DRD', 'MBI', 'MOH', 'ENR', 'CCRN', 'HDSN', 'HLLY',
     'PYCR', 'ONL', 'SCYX', 'CHH', 'ARW', 'VRNA', 'CAR', 'UPBD', 'CYBR', 'SKY', 'OTEX', 'AMAM', 'AMCX',
     'UTZ', 'NVEI', 'WLK', 'IMO', 'BLRX', 'KREF', 'IEX', 'AX', 'MTSI', 'KTB', 'SAFE', 'MNMD', 'NABL',
     'FNKO', 'CABA', 'SUPV', 'CYRX', 'ENFN', 'SCPH', 'INFA', 'AGIO', 'ARVN', 'NUVB', 'PUBM', 'PSFE', 'BSM',
     'MCB', 'CARS', 'BLDE', 'VLN', 'BRC', 'AXTI', 'FNV', 'KLIC', 'ABCB', 'CWAN', 'RSI', 'CGEN', 'EME',
     'UPLD', 'TRTX', 'CEQP', 'SIBN', 'TNK', 'GLOP', 'NSSC', 'UMBF', 'IE', 'BASE', 'ATKR', 'XAIR', 'SAIA',
     'TCBI', 'MXCT', 'MYPS', 'CRNX', 'ARLP', 'HCAT', 'AAT', 'PRG', 'PCTY', 'FMX', 'PRTA', 'BRCC', 'CTMX',
     'SUPN', 'FNGR', 'AMPH', 'AVNT', 'EQIX', 'BFAM', 'GRBK', 'SRG', 'PRCT', 'EVBG', 'AXS', 'SWIM', 'GKOS',
     'EVE', 'MRUS', 'ANSS', 'KLTR', 'CRSR', 'WGO', 'BLCO', 'NGVT', 'TSE', 'CASA', 'CPA', 'DSX', 'MASI',
     'AMPY', 'BECN', 'STE', 'AKLI', 'ORLY', 'MIDD', 'DECK', 'MELI', 'BIPC', 'SLF', 'GEL', 'OM', 'CNNE',
     'PHR', 'ATHM', 'NIU', 'AWI', 'VRNT', 'CRS', 'CHRD', 'EGBN', 'VRSN', 'NDLS', 'EPC', 'CDZI', 'RGLD',
     'API', 'EMBC', 'WIMI', 'ARCT', 'ARCH', 'SANM', 'WVE', 'TILE', 'VSAT', 'OEC', 'PUK', 'SWI', 'GVA',
     'MOD', 'CSAN', 'GLDD', 'ESNT', 'DMTK', 'KRON', 'ORAN', 'RYAAY', 'HUMA', 'MLI', 'AMBC', 'TPC', 'WDS',
     'THCH', 'TWI', 'ENOV', 'PCH', 'EVC', 'ADVM', 'POST', 'GATO', 'BZUN', 'FORM', 'PAX', 'RXST', 'LIVN',
     'MGRM', 'HT', 'ITT', 'TG', 'TRN', 'NICE', 'APLT', 'POOL', 'CRNC', 'BNED', 'CGNT', 'CIR', 'NKTX',
     'INSP', 'WOW', 'ODP', 'CBU', 'PSN', 'EVR', 'CSL', 'SCWO', 'ENV', 'AIZ', 'BAND', 'POWI', 'BKH', 'UMH',
     'CRGY', 'HUBB', 'GTE', 'KRTX', 'RGNX', 'KNSA', 'DENN', 'MTH', 'HRT', 'LRN', 'LAMR', 'WST', 'ZG',
     'GMAB', 'TNET', 'UROY', 'PRME', 'RRX', 'GBX', 'FARO', 'SA', 'RRGB', 'FPI', 'ROOT', 'MAX', 'FN',
     'AMLI', 'SRCL', 'ORA', 'IDXX', 'NTCT', 'TRVI', 'PRQR', 'BSAC', 'PSO', 'LOVE', 'RGA', 'LVO', 'AAC',
     'PRA', 'CHDN', 'MUX', 'BLBD', 'CHMI', 'SNX', 'CVGI', 'MATV', 'NPWR', 'MSM', 'VNOM', 'ASGN', 'SITM',
     'ARGO', 'EWCZ', 'OCUP', 'ESS', 'LIND', 'NOTV', 'HRI', 'OLED', 'ACRO', 'TRVG', 'OMCL', 'GMRE', 'CLH',
     'MAN', 'CVLT', 'MEDP', 'HZO', 'OGS', 'IDCC', 'KMPR', 'INGN', 'SLVM', 'MAIN', 'MDGL', 'UTHR', 'HTBK',
     'IVVD', 'ADCT', 'ERII', 'USM', 'RS', 'WSO', 'LX', 'TUYA', 'WK', 'BKE', 'ONTF', 'QDEL', 'CNTB', 'TFSL',
     'PHAT', 'TRMD', 'IRTC', 'LECO', 'JLL', 'AVTA', 'EXAI', 'EPM', 'PRGS', 'COLM', 'CNMD', 'XENE', 'GMS',
     'SSP', 'ASUR', 'ATAT', 'INBX', 'YMAB', 'GLT', 'TKC', 'NGG', 'ABM', 'DEO', 'AYI', 'QTRX', 'TBBK',
     'ZYXI', 'MLM', 'HEI', 'VAC', 'LZB', 'MPAA', 'JYD', 'RSKD', 'DY', 'TMCI', 'ICAD', 'FLNG', 'CRCT',
     'RACE', 'INGR', 'ORIC', 'HE', 'STBX', 'NMIH', 'OBE', 'PEN', 'ZD', 'CWEN.A', 'GCO', 'WNS', 'CLFD',
     'EPOW', 'HPK', 'MKTX', 'PFSI', 'ALCC', 'MANH', 'OLMA', 'DAKT', 'CMTL', 'THS', 'AFG', 'MTN', 'NXGN',
     'ATGE', 'PRDO', 'KRNT', 'APPN', 'VERX', 'SRRK', 'BIP', 'CUE', 'ZBRA', 'PLAO', 'IGMS', 'PMVP', 'RYI',
     'ASLE', 'EXP', 'COOK', 'CSWC', 'CTAS', 'MNTK', 'VREX', 'VCTR', 'BALY', 'VICR', 'BV', 'HTH', 'ZIMV',
     'ONDS', 'CATY', 'GOLF', 'JACK', 'VSTM', 'COLL', 'CMP', 'QLYS', 'NRIX', 'NGMS', 'CECO', 'TRMK', 'AMRC',
     'FBRT', 'INTR', 'UFPI', 'MRTN', 'PLL', 'CBT', 'SCVL', 'WSR', 'VRA', 'HBIO', 'LAD', 'MMS', 'MESA',
     'CTLP', 'HIBB', 'LII', 'AAN', 'AAIC', 'NEGG', 'NSIT', 'HII', 'RAPT', 'SAIC', 'OCFC', 'KRP', 'CWST',
     'FA', 'SASR', 'EVTL', 'MHO', 'STXS', 'NGM', 'BCC', 'AAON', 'BAP', 'NNBR', 'KEX', 'BZH', 'CWT', 'FUL',
     'RMNI', 'BJRI', 'CTOS', 'TRIN', 'BKNG', 'ITRI', 'KVSA', 'WWD', 'GTY', 'DLB', 'CLAR', 'FFBC', 'PWP',
     'HI', 'AHH', 'WEX', 'MX', 'TM', 'WSBC', 'VCEL', 'CMTG', 'SKYX', 'IIPR', 'GRCL', 'SPRO', 'RLI', 'IBTX',
     'HBNC', 'ELP', 'ZVRA', 'SAH', 'PAG', 'XNCR', 'CGEM', 'TREE', 'DAVA', 'CARM', 'RCI', 'DZSI', 'MHLD',
     'PEGA', 'KFY', 'QIPT', 'KRYS', 'AESI', 'PFMT', 'MCS', 'HNI', 'ALXO', 'PRO', 'STER', 'ACTG', 'LDI',
     'STVN', 'BLFS', 'MITK', 'ONTO', 'ORLA', 'FNA', 'TGH', 'MMYT', 'REYN', 'ITOS', 'ANGO', 'RTO', 'SRAD',
     'TTEK', 'ATLX', 'BBW', 'MATX', 'AQMS', 'LOB', 'SNA', 'APYX', 'RILY', 'MUSA', 'HYPR', 'PX', 'VLRS',
     'BHR', 'R', 'MTW', 'CMG', 'GAN', 'VC', 'NUVL', 'TAC', 'LAB', 'SSL', 'HSAI', 'IHS', 'SIGI', 'PRIM',
     'ALKT', 'MOND', 'ALTR', 'DGII', 'CNOB', 'COO', 'STEP', 'SITE', 'OVID', 'NN', 'CHEF', 'SFBS', 'DSKE',
     'STRL', 'PSNL', 'MNRO', 'SR', 'AMR', 'AVAH', 'FSS', 'TMST', 'ENSG', 'LRMR', 'LUNG', 'WSFS', 'TFX',
     'NXST', 'WEST', 'SEER', 'ACEL', 'HAE', 'NS', 'ALE', 'TCMD', 'RCEL', 'MEOH', 'ARCB', 'SACH', 'FDS',
     'FRME', 'IMAB', 'GOOD', 'CASY', 'HEAR', 'HFWA', 'EGP', 'AMPX', 'LNZA', 'UCTT', 'XPER', 'NWE', 'MMSI',
     'BMA', 'EGLE', 'TITN', 'INTT', 'PBPB', 'BSGM', 'MODN', 'EPAC', 'OSPN', 'GDOT', 'HUIZ', 'CCOI', 'BGFV',
     'ANDE', 'GWW', 'SMSI', 'BDC', 'ATHA', 'GHL', 'LUNA', 'EVTC', 'AB', 'PKX', 'PTVE', 'PANL', 'ATRC', 'E',
     'DWAC', 'HEES', 'IPX', 'KITT', 'EEFT', 'BHLB', 'DSGN', 'AACT', 'NSP', 'HNRG', 'CRNT', 'ADTH', 'IMXI',
     'SIEB', 'FIX', 'SBOW', 'SPXC', 'LOMA', 'TNP', 'TOUR', 'INDB', 'AVNS', 'TFII', 'FEAM', 'UBA', 'WIRE',
     'LYTS', 'TDG', 'BHG', 'DIN', 'ARAV', 'RBOT', 'AREC', 'KRNY', 'SPTN', 'CBAT', 'HMN', 'SOI', 'LASR',
     'TDY', 'ACT', 'LILA', 'ATR', 'EXLS', 'ARIS', 'AZPN', 'TTGT', 'KLR', 'ATNM', 'SCRM', 'SPOK', 'BPT',
     'TYL', 'LAW', 'ENS', 'EXPO', 'BOOM', 'GLYC', 'AIP', 'STOK', 'AUDC', 'AZRE', 'IMCR', 'VIRX', 'GRND',
     'FWRG', 'OFG', 'IMNM', 'SKIL', 'FCN', 'LBAI', 'FOXF', 'HUBG', 'ALRM', 'CYT', 'URGN', 'IVT', 'MDXH',
     'AKYA', 'VAXX', 'NBR', 'BCLI', 'SKYT', 'RMBL', 'BEP', 'KLXE', 'TLYS', 'RNST', 'AGO', 'SHYF', 'CMPS',
     'NBHC', 'TRUE', 'WD', 'ATXS', 'VITL', 'RDY', 'FG', 'LSTR', 'NDSN', 'ELVN', 'ARKO', 'DFH', 'RBC',
     'ACA', 'EMBK', 'BLD', 'APEI', 'DCOM', 'CEPU', 'CCS', 'KORE', 'DIOD', 'ALEX', 'COHU', 'CONN', 'LANV',
     'AOSL', 'MEI', 'PORT', 'MED', 'VMD', 'GASS', 'IPGP', 'CURO', 'BIVI', 'NFGC', 'SY', 'PRDS', 'UVE',
     'OFIX', 'ICVX', 'PBYI', 'ENTA', 'CLDT', 'TOWN', 'ITGR', 'IBOC', 'AVAV', 'RVPH', 'KROS', 'LPTV',
     'NTGR', 'PBH', 'TX', 'KNDI', 'PAYS', 'ABG', 'DESP', 'ESAB', 'MASS', 'AMG', 'FF', 'HTLF', 'GGR', 'KB',
     'RERE', 'GLUE', 'AFYA', 'BGNE', 'MCY', 'DLX', 'KRO', 'CPF', 'RDW', 'NXDT', 'VOR', 'PRFT', 'CURV',
     'LIAN', 'TCOA', 'OXM', 'RELL', 'TNGX', 'PPTA', 'AIRS', 'ARBK', 'BIO', 'AMSWA', 'BANR', 'VRCA', 'WNNR',
     'FUN', 'BOKF', 'REVG', 'IBP', 'BLKB', 'MEG', 'ALCYU', 'TFPM', 'EVCM', 'TARS', 'KNTK', 'LTC', 'CLBT',
     'FLGT', 'CRTO', 'UHAL', 'PXLW', 'PAR', 'CTS', 'CMLS', 'CLBK', 'EWTX', 'DRQ', 'ARGX', 'SRTS', 'IRON',
     'RLMD', 'CASH', 'BFAC', 'PJT', 'LFMD', 'CENTA', 'NHI', 'TBI', 'HLNE', 'AMTD', 'MMI', 'TUSK', 'ANAB',
     'CBZ', 'KALV', 'SATS', 'PLYM', 'CAE', 'SPH', 'AGTI', 'KEP', 'TR', 'GCMG', 'ALGT', 'XPDB', 'FICO',
     'SND', 'CPS', 'LOPE', 'KNSL', 'GLPG', 'CSTE', 'IPI', 'FBNC', 'HAFC', 'DC', 'HHC', 'FCFS', 'HONE',
     'ETD', 'IZM', 'BCO', 'PETQ', 'FOA', 'RRAC', 'BUSE', 'FFIC', 'HTLD', 'SJW', 'KELYA', 'BEEM', 'KCGI',
     'STC', 'ABOS', 'NBTB', 'B', 'ITI', 'GSHD', 'AIXI', 'NFNT', 'WABC', 'AWR', 'THG', 'CMPO', 'BHE', 'FDP',
     'QUAD', 'LE', 'PLG', 'EE', 'INKT', 'IDA', 'GRNT', 'HMPT', 'LAND', 'NFBK', 'IVAC', 'AEIS', 'JFIN',
     'SCHN', 'EGRX', 'MTLS', 'TGS', 'BIOR', 'BCSF', 'SKWD', 'XNET', 'AZO', 'KNOP', 'AMSC', 'HEP', 'UEIC',
     'TFIN', 'ECPG', 'CNDA', 'ENVA', 'CITE', 'LCII', 'STEL', 'LGIH', 'OSBC', 'BCYC', 'VZLA', 'AGYS',
     'GDEN', 'THCP', 'GBTG', 'SURG', 'GBIO', 'PDFS', 'MMMB', 'WGS', 'JRVR', 'BCOV', 'OTTR', 'BMI', 'GRPH',
     'AVD', 'BELFB', 'PPSI', 'ALPN', 'FELE', 'AIT', 'EFSC', 'KOF', 'ROAD', 'UFI', 'GNE', 'LKFN', 'BRDG',
     'CLPT', 'CNA', 'TPB', 'FBK', 'ACHV', 'AORT', 'TLK', 'SPSC', 'ICHR', 'PFC', 'APOG', 'STBA', 'PRLB',
     'DIBS', 'AMRK', 'PWUP', 'JOE', 'AMEH', 'YALA', 'FLIC', 'LCAA', 'ASIX', 'FRHC', 'ICUI', 'THR', 'BWEN',
     'AFCG', 'SCHL', 'CNS', 'NVGS', 'FIZZ', 'ECX', 'ADUS', 'BSIG', 'AXGN', 'DFIN', 'MORN', 'ABEO', 'BOLT',
     'LGVN', 'ROCK', 'CTRN', 'CVM', 'ATRO', 'TTEC', 'DBVT', 'CINT', 'CSGS', 'GPOR', 'MTX', 'THRX', 'NX',
     'AMAL', 'LPTH', 'OMGA', 'FWRD', 'WOR', 'GROV', 'RDWR', 'CODI', 'KFRC', 'AJX', 'RPHM', 'NWN', 'IOBT',
     'PAM', 'ESTA', 'AVO', 'RNGR', 'DSGX', 'MOV', 'KRUS', 'AIN', 'DDS', 'SIFY', 'BOC', 'CACI', 'SSD',
     'LINC', 'PRLH', 'GODNU', 'CVRX', 'LTRX', 'SPRB', 'ARBE', 'GPI', 'WASH', 'FCUV', 'PLSE', 'ICCM',
     'TZOO', 'MEC', 'MOR', 'IVA', 'CRDF', 'SUN', 'CCSI', 'LPL', 'ASMB', 'PLMR', 'JBT', 'SBSI', 'AIR',
     'MLNK', 'MG', 'RLGT', 'ENZ', 'PNTG', 'FCNCA', 'DHX', 'LMB', 'CRESY', 'CTO', 'CWCO', 'INVE', 'TIXT',
     'PDLB', 'CFFS', 'TRHC', 'STIM', 'CNTA', 'ATEX', 'GATX', 'MCFT', 'GPRK', 'GEF', 'MLYS', 'VMI', 'CW',
     'MYTE', 'MSEX', 'HRTG', 'PEBO', 'AMK', 'LANC', 'THRM', 'ZVIA', 'STRA', 'RGS', 'RSVR', 'MBUU', 'MSA',
     'SHIP', 'DAC', 'HCKT', 'EIG', 'JUN', 'CMCA', 'PSMT', 'SRI', 'PVBC', 'KRMD', 'MGTX', 'CQP', 'VVI',
     'PATK', 'ARC', 'DRRX', 'DMRC', 'AZ', 'ALPA', 'METCB', 'LBPH', 'HVT', 'IHG', 'VTOL', 'GIB', 'MESO',
     'OCFT', 'QNCX', 'HURN', 'JAKK', 'CCVI', 'ATEK', 'INBK', 'MOG.A', 'III', 'IPAR', 'ROG', 'LQDT', 'GPCR',
     'CEVA', 'FOR', 'PBT', 'LBRDA', 'PLUS', 'MODV', 'CLW', 'JGGC', 'IIIV', 'BLZE', 'JANX', 'REAX', 'GAMB',
     'CMPR', 'ERIE', 'HITI', 'ANIP', 'GFGD', 'PRI', 'PSTL', 'NOVT', 'XPEL', 'INST', 'STHO', 'SLAM', 'HLIO',
     'CAAP', 'NPO', 'VRAR', 'MSGS', 'LEU', 'BIOS', 'CVGW', 'CBRG', 'PLXS', 'FENC', 'OB', 'NVMI', 'SXT',
     'CHUY', 'BCH', 'VNRX', 'DMAC', 'MYE', 'LVLU', 'BCTX', 'DRIO', 'LYRA', 'MHUA', 'BMRC', 'HSHP', 'IMRX',
     'SCL', 'DPCS', 'SHCO', 'DXPE', 'OSIS', 'FBMS', 'NEWP', 'NXPL', 'OPRX', 'CLSD', 'DTI', 'SHG', 'BLFY',
     'USGO', 'HSII', 'SGHT', 'DOOR', 'VMCA', 'USAC', 'CCAP', 'SPNS', 'LMAT', 'WFG', 'AADI', 'SCSC', 'MTD',
     'MGPI', 'WMK', 'ZING', 'HCM', 'NRT', 'BTMD', 'LXFR', 'KALU', 'BWC', 'BSAQ', 'PLOW', 'UVV', 'FMNB',
     'IXHL', 'MKTW', 'ARBB', 'SAM', 'CFB', 'MTAL', 'LCUT', 'ZAPP', 'PRLD', 'SYBT', 'MGEE', 'WRAP', 'UFPT',
     'CIA', 'KAMN', 'USPH', 'ERO', 'BATRK', 'VOXX', 'TRTL', 'LSEA', 'VRTV', 'SST', 'TRIS', 'NXRT', 'SHEN',
     'GDHG', 'PFTA', 'IKNA', 'OBK', 'WTS', 'APPF', 'MATW', 'INSE', 'HOLI', 'NAUT', 'OOMA', 'GILT', 'SMHI',
     'EPSN', 'CHCT', 'AMWD', 'RGR', 'MGRC', 'FWAC', 'TEO', 'ARTE', 'LAES', 'OPAL', 'MACK', 'STKS', 'FLL',
     'MYRG', 'WPP', 'BWB', 'TRDA', 'SHAP', 'PINE', 'CLCO', 'DCO', 'ESE', 'UTAA', 'CCU', 'UVSP', 'RWAY',
     'NECB', 'PFSW', 'SGTX', 'PIPR', 'MIST', 'OLK', 'LMNR', 'NVEE', 'BBCP', 'NFYS', 'FWONA', 'UTI', 'AZZ',
     'VTSI', 'ASPS', 'LVOX', 'GLRE', 'TIGO', 'ZEUS', 'PFBC', 'GNFT', 'BRD', 'TCX', 'BLX', 'RPTX', 'HSTM',
     'EBF', 'CELC', 'XYF', 'CMBM', 'IPSC', 'FHTX', 'ADRT', 'BY', 'CMCL', 'PVL', 'SLP', 'DORM', 'TYGO',
     'ANTX', 'TRS', 'LGND', 'TTSH', 'REFI', 'WDFC', 'ANIX', 'SRDX', 'HGTY', 'PWFL', 'OPAD', 'RLYB', 'NMM',
     'SCWX', 'HY', 'EVGR', 'SHBI', 'LAZY', 'BANF', 'KWR', 'BXC', 'BTDR', 'TRST', 'TIPT', 'CAMT', 'HWEL',
     'XBIT', 'EEX', 'AMSF', 'ALVO', 'IDT', 'LNN', 'MCRI', 'TCBK', 'ALLG', 'AOMR', 'KVHI', 'KFS', 'CBL',
     'HLVX', 'RMAX', 'PAHC', 'CIGI', 'IBEX', 'ALYA', 'NMG', 'NB', 'INFU', 'ONEW', 'CMCO', 'BYN', 'BWMN',
     'CDRE', 'BYRN', 'CFIV', 'BCPC', 'KIDS', 'PESI', 'KNW', 'KE', 'FACT', 'AVTE', 'TNC', 'EVEX', 'CHT',
     'IBCP', 'AURA', 'ARCE', 'CSV', 'FISI', 'SLNA', 'ICFI', 'IIIN', 'WSBF', 'CAAS', 'SMP', 'ML', 'RMR',
     'LUXH', 'WKME', 'FC', 'SNEX', 'MTRN', 'DLTH', 'GABC', 'POWL', 'IRS', 'PHYT', 'DSP', 'SCU', 'IPA',
     'HIPO', 'SMWB', 'DGHI', 'ELTX', 'LFUS', 'REPX', 'CLMT', 'BCBP', 'PKE', 'AMTB', 'CDXC', 'REX', 'TKNO',
     'JYNT', 'PMTS', 'MRAM', 'AREN', 'IOSP', 'IVCP', 'OMAB', 'EARN', 'SYRS', 'TSQ', 'IMKTA', 'FET', 'PHX',
     'ANIK', 'UI', 'SSTI', 'SONX', 'CPSI', 'MITT', 'AVAL', 'DMLP', 'FRGI', 'ASTE', 'CMT', 'HCCI', 'EDAP',
     'GOCO', 'CHCO', 'GLP', 'CPK', 'OBIO', 'VII', 'PRPH', 'VOC', 'AGX', 'UFCS', 'OPY', 'RCMT', 'CAPR',
     'UAN', 'GP', 'UTL', 'BAER', 'FLME', 'MSBI', 'FRST', 'GPP', 'TESS', 'SUAC', 'CSR', 'MBIN', 'CRMT',
     'GANX', 'NEXA', 'HOFT', 'PARAA', 'GLTO', 'BFST', 'GLTA', 'NETC', 'AVNW', 'CATO', 'BTWN', 'PAY',
     'VIGL', 'PKOH', 'ENLT', 'SQNS', 'BRT', 'BDSX', 'SENEA', 'HWKN', 'VVX', 'SXI', 'JBSS', 'KOP', 'CVLG',
     'MTRX', 'CARE', 'PGC', 'ISPR', 'IVCB', 'PFIE', 'SGC', 'NAMS', 'LOCC', 'EGGF', 'SP', 'MNTN', 'LGVC',
     'USNA', 'TYRA', 'YI', 'CCNE', 'WNEB', 'CHE', 'SUP', 'SLVR', 'NGS', 'EMLD', 'CLIN', 'EGAN', 'PNAC',
     'HCI', 'GIC', 'LITB', 'PCYO', 'SRCE', 'CASS', 'TRMR', 'SAFT', 'CACC', 'UONE', 'CNXN', 'JJSF', 'VEON',
     'CLIR', 'RANI', 'OLP', 'VANI', 'ATS', 'WRLD', 'FRBA', 'TBMC', 'BIOX', 'UNF', 'QCRH', 'PET', 'WALD',
     'SOPH', 'HOV', 'GHRS', 'CSTR', 'NVCT', 'CBUS', 'FORR', 'THRD', 'AFTR', 'XPAX', 'MHH', 'STN', 'PAC',
     'CVCO', 'NOAH', 'BCAN', 'TGAN', 'ALLT', 'VPG', 'PEGR', 'CABO', 'CCLP', 'FSV', 'FUSN', 'NEOV', 'ODV',
     'MOVE', 'AROW', 'PEPG', 'CAC', 'THFF', 'NOA', 'SVII', 'BWAQ', 'FNVT', 'ASR', 'EFXT', 'FMBH', 'CREC',
     'GALT', 'ADSE', 'BYFC', 'PDS', 'HFFG', 'CTSO', 'CNTY', 'ARIZ', 'SBR', 'GRC', 'CBAN', 'QSG', 'LTBR',
     'LUCD', 'CLPR', 'CVCY', 'LGO', 'PHI', 'AGM', 'SEVN', 'OESX', 'GENC', 'OPFI', 'RBB', 'TARO', 'ICNC',
     'DOOO', 'SATL', 'TGAA', 'NWPX', 'SMLR', 'GB', 'KAI', 'SNFCA', 'YRD', 'UHG', 'TDCX', 'IFS', 'NUBI',
     'CTBI', 'VINP', 'BVH', 'JILL', 'PRK', 'XOMA', 'NPAB', 'BSRR', 'CANG', 'NREF', 'WPRT', 'ALG', 'SKE',
     'FANH', 'CLLS', 'ROCL', 'ALRS', 'CETY', 'CSWI', 'DRTS', 'CCV', 'HAYN', 'WWAC', 'EPIX', 'FLUX', 'PCTI',
     'ATLO', 'FPH', 'FLGC', 'LBC', 'NVEC', 'CRGO', 'VRTS', 'MLAB', 'ELTK', 'UHT', 'LCW', 'NEON', 'DCTH',
     'PMGM', 'MVBF', 'AMOT', 'MVO', 'NHC', 'CCB', 'EZGO', 'VHNA', 'LSAK', 'ARTNA', 'USAP', 'CENT', 'NNI',
     'BBUC', 'ULH', 'ORTX', 'ETON', 'NIC', 'EQBK', 'CRT', 'NWTN', 'FCBC', 'LOOP', 'SGU', 'TMP', 'FATP',
     'MCBC', 'BCML', 'ODC', 'SEDA', 'TSBK', 'MOBV', 'ESGR', 'OMEX', 'NVX', 'MPB', 'INMB', 'SOHU', 'BATRA',
     'CCRD', 'CVEO', 'LND', 'ELA', 'LVWR', 'IESC', 'DALS', 'GRIN', 'ALSA', 'OPA', 'ANVS', 'ESCA', 'SNPO',
     'LFAC', 'INCR', 'RCFA', 'MKUL', 'JHX', 'OCN', 'GNLX', 'CDAQ', 'HCTI', 'NGVC', 'HAIA', 'LCNB', 'ASCB',
     'HQI', 'CAPL', 'STIX', 'ISTR', 'NRIM', 'CATC', 'TCBX', 'FRBN', 'YTRA', 'ORN', 'LFT', 'RGCO', 'AIU',
     'MOFG', 'CPUH', 'ARYE', 'WF', 'RICK', 'LEGH', 'SLND', 'SFST', 'BFS', 'MPX', 'BNR', 'CYD', 'RCKY',
     'CODA', 'SKGR', 'HOWL', 'ATNI', 'THRN', 'DCBO', 'GFOR', 'CRVL', 'YORW', 'GNSS', 'FORL', 'BCDA', 'EDN',
     'NRC', 'AEAE', 'GLSI', 'CMCT', 'RFL', 'HTBI', 'KMDA', 'WMPN', 'WTBA', 'SBT', 'INTE', 'SPFI', 'CPLP',
     'GIFI', 'COKE', 'OVLY', 'FCCO', 'STRM', 'MBWM', 'REFR', 'INNV', 'SANW', 'NWFL', 'WLDN', 'VSEC',
     'IGIC', 'PCYG', 'SOS', 'MSB', 'FGBI', 'BHB', 'FVCB', 'FSBC', 'QUIK', 'AOUT', 'ESSA', 'MNSB', 'WLKP',
     'CVLY', 'TRC', 'LTRN', 'BLTE', 'BBSI', 'TBNK', 'GEG', 'UONEK', 'CRAI', 'MMLP', 'NBN', 'OSS', 'VGAS',
     'VSTA', 'BHM', 'BRKH', 'DYAI', 'HHLA', 'GHI', 'FSBW', 'CIVB', 'DLNG', 'CPSS', 'QRHC', 'DGICA', 'PHVS',
     'MKL', 'JOUT', 'APCA', 'ENTF', 'IVCPU', 'MLR', 'MLP', 'SMBK', 'CCF', 'KRT', 'ALCO', 'GWRS', 'MYNZ',
     'PCB', 'IRMD', 'KYCH', 'DKL', 'USCT', 'MBCN', 'NEU', 'CCBG', 'SCAQ', 'CTG', 'GFX', 'LVRO', 'GBBK',
     'STTK', 'VOXR', 'PROF', 'POET', 'MCBS', 'EFHT', 'MRBK', 'ACRV', 'OPBK', 'SSBK', 'LFVN', 'SHUA',
     'RZLT', 'FTHM', 'TPL', 'RM', 'AMBI', 'NATR', 'QRTEB', 'TACT', 'FRXB', 'CZNC', 'TRNS', 'GNTY', 'SERA',
     'FICV', 'VBOC', 'GSBC', 'RCLF', 'SJ', 'EVBN', 'ESQ', 'RAIL', 'SLDB', 'GEOS', 'BYNO', 'SMBC', 'FTII',
     'EVI', 'SMMF', 'SRT', 'BSET', 'FAT', 'DBTX', 'TWOA', 'FSNB', 'AOGO', 'ITRN', 'MCAC', 'DAVE', 'CNF',
     'GMGI', 'AXAC', 'BGI', 'PTWO', 'MCHX', 'EAR', 'SAMG', 'SMTI', 'BHRB', 'ASYS', 'PWOD', 'BWMX', 'PRTH',
     'COFS', 'FRLA', 'RVSB', 'GHM', 'FZT', 'TRCA', 'ACAB', 'NVR', 'NKSH', 'RDVT', 'AFRI', 'IX', 'ADAG',
     'FNCB', 'HURC', 'MGIC', 'OBT', 'DLHC', 'YOTA', 'LOAN', 'AMNB', 'BPRN', 'EP', 'XPAXU', 'AQU', 'INDV',
     'KTCC', 'LAKE', 'XLO', 'VIRC', 'ESLT', 'TPCS', 'UNTY', 'WINA', 'AAMC', 'BSVN', 'DSGR', 'VLGEA',
     'FRPH', 'CLRC', 'BWFG', 'NPK', 'GRVY', 'WMC', 'BLNG', 'FMAO', 'PTSI', 'CZFS', 'PERF', 'BFC', 'VTRU',
     'PLBC', 'BGSF', 'OCS', 'SSU', 'FSTR', 'APTM', 'CCTS', 'CVV', 'PUCK', 'PKBK', 'NYXH', 'WEL', 'NL',
     'IGTA', 'HOFV', 'RBCAA', 'CXAC', 'JMSB', 'USCB', 'LNKB', 'CPTK', 'TETE', 'HIFS', 'CHMG', 'MDWT',
     'VACC', 'TSAT', 'FORA', 'MIXT', 'MNOV', 'ATLC', 'UBFO', 'CBNK', 'MSSA', 'IMOS', 'GGAA', 'CULP', 'VEL',
     'HCWB', 'AEYE', 'GATE', 'ULBI', 'BATL', 'TXO', 'EVO', 'MYFW', 'KEN', 'RMBI', 'ARRW', 'RSSS', 'EBTC',
     'ROSE', 'ESEA', 'CTGO', 'SELF', 'FDBC', 'OFLX', 'AP', 'TLGA', 'ACAX', 'HHRS', 'ZTEK', 'BBDO', 'WLFC',
     'MNTX', 'DLA', 'IRRX', 'HBB', 'GHC', 'ORRF', 'SNAL', 'NRP', 'CSTA', 'MLEC', 'IDR', 'BFIN', 'HNRA',
     'VBNK', 'PLPC', 'SGA', 'GCBC', 'FNLC', 'NPCE', 'AIRG', 'FUNC', 'ECBK', 'AC', 'FNWB', 'GDEV', 'HYW',
     'SGII', 'TWIN', 'FBIZ', 'SLGL', 'ALX', 'PGSS', 'SCX', 'MDWD', 'COOL', 'CFFI', 'ENER', 'VHI', 'SILC',
     'CDRO', 'MDV', 'FGMC', 'NTIC', 'STRS', 'IONR', 'NC', 'BRAG', 'PBFS', 'HBCP', 'LATG', 'NHTC', 'ITCL',
     'ISSC', 'ACR', 'VSAC', 'TROO', 'SKYH', 'UBP', 'IPWR', 'NWLI', 'SSBI', 'CRWS', 'RMGC', 'BCAL', 'FMIV',
     'RDI', 'PEBK', 'IPHA', 'PROC', 'FIAC', 'FRD', 'NATH', 'FEXD', 'SLAC', 'TGVC', 'PFIS', 'AACI', 'GENQ',
     'NBST', 'KRNL', 'MSC', 'FRAF', 'FINW', 'HWBK', 'RTC', 'AGAC', 'APMIU', 'ACNB', 'BACA', 'MBAC', 'BNRE',
     'VALN', 'BCSA', 'NODK', 'DDI', 'IH', 'BKTI', 'GLLI', 'ALOT', 'JAQC', 'ELMD', 'LWAY', 'WEYS', 'DHIL',
     'ATAK', 'GPAC', 'BBU', 'ATAQ', 'CLGN', 'ICG', 'ALTU', 'SWSS', 'ARM', 'RDDT', 'ALAB', 'IBTA']

active_instruments = all_by_three_month_average_trading_volume
active_etfs = all_etfs